$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command
code: src/
command: >-
  python index.py \
    --data_path ${{inputs.data}} \
    --output_dir ${{outputs.outputs}} \
    --epochs 1

inputs:
  data:
    type: uri_folder
    path: azureml:battery_data_256_256@latest
    mode: ro_mount

outputs:
  outputs:
    type: uri_folder
    mode: rw_mount

compute: azureml:gpu-t4
environment: azureml:env-yolo@latest
experiment_name: Battery_PatchCore
display_name: "PatchCore Training (CLAHE)"
