$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command
code: src/
# 실제 사용할 때 아래 command 삭제 후, 해당 로직 주석 해제하여 사용하기
# command: >-
#   python index.py \
#     --data_path ${{inputs.data}} \
#     --output_dir ${{outputs.outputs}}
# inputs:
#   data:
#     type: uri_folder
#     path: azureml:[데이터셋이름]@latest
#     mode: ro_mount

command: >-
  python index.py
    --data_path ${{inputs.data}}
    --output_dir ${{outputs.outputs}}
    --sas_token '${{inputs.sas_token}}'
    --blob_path '${{inputs.blob_path}}'
    --epochs ${{inputs.epochs}}

inputs:
  data:
    type: uri_folder
    path: azureml:battery_data_zip@latest
    mode: ro_mount
  sas_token: "sv=2025-07-05&spr=https&st=2026-02-09T02%3A58%3A45Z&se=2026-02-10T02%3A58%3A45Z&sr=c&sp=racwlt&sig=yOIw2fRr86ogubymBq2qQwbs9%2B%2FQvHDhaD8%2BUHaWwro%3D"
  blob_path: "TS_Exterior_Img_Datasets_images_3.zip"
  epochs: 10

outputs:
  outputs:
    type: uri_folder
    # Job 완료 후 자동 업로드
    mode: rw_mount

compute: azureml:gpu-t4
environment: azureml:env-yolo@latest
# Job 실험명과 task 명 지정. 미기재 해도 됨.
experiment_name: Test_Github
display_name: "Test Github"
