$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command
code: src/
command: >-
  python index.py \
    --data_path ${{inputs.data}} \
    --output_dir ${{outputs.outputs}}
inputs:
  data:
    type: uri_folder
    path: azureml:battery_exterior_zip@4
    mode: ro_mount

outputs:
  outputs:
    type: uri_folder
    # Job 완료 후 자동 업로드
    mode: rw_mount

compute: azureml:gpu-t4
environment: azureml:env-yolo@21
# Job 실험명과 task 명 지정. 미기재 해도 됨.
experiment_name: Test_Github
display_name: "Test Github"
