$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json

type: command
code: src/
# 실제 실행될 index.py 파일 실행 명령어
command: >-
  python index.py
  --data_path ${{inputs.data}}
  --output_dir ${{outputs.outputs}}
  --sas_token ${{inputs.sas_token}}
  --blob_path ${{inputs.blob_path}}
  --epochs ${{inputs.epochs}}

inputs:
  data:
    type: uri_folder
    path: azureml:battery_data_zip@latest
    mode: ro_mount
  
  sas_token:
    type: string
    default: "?sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2024-12-31T14:59:59Z&st=2024-01-01T00:00:00Z&spr=https&sig=PLACEHOLDER_SAS_TOKEN"
  
  blob_path:
    type: string
    default: "TS_Exterior_Img_Datasets_images_0.zip"
  
  epochs:
    type: integer
    default: 10

outputs:
  outputs:
    type: uri_folder
    # Job 완료 후 자동 업로드
    mode: rw_mount

compute: azureml:gpu-cluster-t4
# Environment: Build from Dockerfile (using team's uv setup)
environment:
  build:
    path: src
    dockerfile_path: Dockerfile
# Job 실험명과 task 명 지정. 미기재 해도 됨.
experiment_name: Test_Github
display_name: "Test Github"
