$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command
code: src/
command: >-
  python index.py \
    --data_path ${{inputs.data}} \
    --output_dir ${{outputs.outputs}} \
    --epochs 1

inputs:
  data:
    type: uri_folder
    path: azureml:battery_data_256_256@latest
    mode: ro_mount

outputs:
  outputs:
    type: uri_folder
    mode: rw_mount

<<<<<<< HEAD
compute: azureml:gpu-t4

environment: azureml:env-yolo@latest
experiment_name: Patchcore_sungtae
display_name: "Patchcore_sungtae"
=======
compute: azureml:gpu-advanced

environment: azureml:env-yolo@latest
experiment_name: PatchCore
display_name: "PatchCore"
>>>>>>> f13b0e57086b83c8090fa0ab81c91f51c68e3349
