name: anomalib-env
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - libgl-mesa-glx
  - pip:
    - azureml-mlflow
    - loguru
    - omegaconf>=2.1.1
    - rich>=13.5.2
    - jsonargparse[signatures]>=4.27.7
    - docstring_parser
    - rich_argparse
    - lightning>=2.2.0
    - torchmetrics>=1.1.0
    - lightning-utilities
    - timm
    - freia>=0.2
    - einops>=0.3.2
    - pillow>=10.1.0
    - opencv-python-headless>=4.5.3.56
    - scikit-image
    - tifffile
    - imagecodecs
    - kornia>=0.6.6
    - pandas>=1.1.0
    - matplotlib>=3.4.3
    - scikit-learn
    - imgaug
    - anomalib==1.1.3
    - openvino>=2024.0
    - nncf>=2.10.0
    - onnx>=1.16.0
